SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `answers` (
  `id` int(4) NOT NULL,
  `rightAnswer` int(2) NOT NULL,
  `alternativeA` varchar(500) NOT NULL,
  `alternativeB` varchar(500) NOT NULL,
  `alternativeC` varchar(500) NOT NULL,
  `alternativeD` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `answers`
--

INSERT INTO `answers` (`id`, `rightAnswer`, `alternativeA`, `alternativeB`, `alternativeC`, `alternativeD`) VALUES
(1, 1, 'desenvolvimento da política espacial, representada pela primeira viagem em torno da Terra por Gagarin.', '		\r\n	desenvolvimento da indústria cinematográfica e das teorias em torno da fusão nuclear.', '		\r\n	desenvolvimento da indústria automobilística e o incremento do sistema industrial privado.', '		\r\n	crescimento do mercado interno, com o desenvolvimento de novas técnicas de cultivo agrícola e aumento de salários.'),
(2, 4, 'Doutrina Drago.', '		\r\n	Doutrina Monroe.', '		\r\n	Corolário Roosevelt', '		\r\n	Nova Fronteira.'),
(3, 2, 'Na Iugoslávia (1944-45), o regime comunista implantado pelo Marechal Tito submeteu-se à hegemonia política e econômica soviética, o que acarretou sua expulsão do movimento dos países não alinhados.', '		\r\n	b) Na Tchecoslováquia (1946), o socialismo reformista, baseado na descentralização e liberalização do sistema frente ao modelo stalinista, retomado na política de Brejnev, foi interrompido pela repressão russa, encerrando a "Primavera de Praga".', '		\r\n	c) Na China (1949), a revolução comunista derrubou o regime imperial e expulsou os invasores japoneses da Manchúria, reunindo os nacionalistas, os "senhores da guerra" e os comunistas maoístas em um governo de coalizão que instituiu uma república popular no país.', '		\r\n	d) Na Coréia (1950-53), a intervenção militar norte-americana impediu o avanço das forças revolucionárias comunistas que ocupavam o norte do país, reunificando as duas Coréias sob a tutela do Conselho de Segurança da ONU.'),
(4, 4, 'enfraquecimento dos movimentos nacionalistas regionais e das tendências de globalização na Europa ocidental.', '		\r\n	b) declínio da liderança política internacional das superpotências em virtude da transferência do controle de seus arsenais nucleares para a Assembléia Geral da ONU.', '		\r\n	c) revitalização das alianças militares estratégico-defensivas, conforme os pactos políticos da Europa central e do leste.', '		\r\n	d) formação de megablocos político-econômicos que favoreceram a internacionalização dos fluxos de capitais, tais como a da Comunidade Européia e a do Nafta.'),
(5, 1, 'conflito político e ideológico entre a União Soviética e os Estados Unidos.', '		b) supremacia política e militar da Europa Ocidental.\r\n	', '		\r\n	c) subordinação neocolonial dos países árabes e da América Latina.', '		\r\n	d) liderança política mundial da China Comunista através de sua participação na ONU.'),
(6, 2, 'o Comecom', '		\r\n	o Kominform', '		\r\n	o Pacto de Varsóvia', '		\r\n	o Plano Marshall'),
(7, 4, 'assegurava a penetração de capitais  norte-americanos no continente europeu, sobretudo em sua parte oriental.', '		\r\n	garantia, aos norte-americanos, o retorno a uma política isolacionista, voltada unicamente para os seus interesses internos.', '		pretendia deter as ameaças soviéticas sobre os países do Oriente Médio, cuja produção de petróleo era vital para as economias ocidentais.\r\n	', '		\r\n	era um instrumento decisivo na luta contra o avanço do comunismo na Europa arrasada pelo pós-guerra.'),
(8, 1, 'o temor trazido pela criação do Mercado Comum Europeu (MCE);', '		\r\n	o deslocamento do controle do capitalismo da Europa para os EUA e sua crescente influência sobre os países europeus;', '		\r\n	a necessidade que a Europa tinha de reunir recursos para pagar o seu principal credor, os EUA, que lhe forneceram desde alimentos até materiais bélicos durante a II Guerra Mundial;', '		\r\n	a necessidade de se reconstruírem as cidades e de recuperarem a indústria e a agropecuária européia, devastadas durante a II Grande Guerra;'),
(9, 5, 'corrida armamentista entre as potências imperialistas européias ocasionando a Primeira Guerra Mundial.', '		\r\n	domínio dos países socialistas do Sul do globo pelos países capitalistas do Norte.', '		\r\n	choque ideológico entre a Alemanha Nazista / União Soviética Stalinista, durante os anos 30.', '		\r\n	disputa pela supremacia da economia mundial entre o Ocidente e as potências orientais, como a China e o Japão.'),
(10, 4, 'somente I.', 'somente I e II.', '	\r\n	I, II e III.', 'somente II e III.'),
(11, 2, 'a Doutrina Monroe e a Organização da Nações Unidas (ONU).', 'o Plano Marshall e a organização do Tratado do Atlântico Norte (OTAN).', 'o Pacto de Varsóvia e a Comunidade Econômica Européia (CEE).\r\n	', 'o Pacto do Rio de Janeiro e o Conselho de Assistência Econômica Mútua (COMECON).\r\n	'),
(12, 2, 'Truman (1945 - 52), encerrou-se a política macarthista, o que possibilitou o fim da Guerra da Coréia e sua conseqüente unificação sob um protetorado norte-americano.		\r\n	', 'Eisenhower (1952 - 60), completou-se o sistema de segurança norte-americano, com a formação de diversos pactos militares contra os comunistas.		\r\n	', 'Kennedy (1960 - 63), desenvolvendo a "Aliança para o Progresso" encerrou-se a política de confronto com o mundo comunista, permitindo a retirada americana do conflito vietnamita.		\r\n	', 'Johnson (1963 - 68), a discussão da Doutrina Monroe consolidou-se as alianças políticas com os movimentos nacionalistas e o fim das intervenções militares na América Latina.		\r\n	'),
(13, 2, 'o desaparecimento de Joseph Stálin (1953), acompanhado da ascensão de Malenkov, conduziu a um recrudescimento da Guerra Fria, instigando a participação soviética em disputas por áreas como a Letônia e o Vietnã.		\r\n	', 'o Governo de Kruschev (1955-64) correspondeu a uma época de críticas às práticas políticas do Stalinismo e à negação, por parte da URSS, da inevitabilidade da Guerra com os países capitalistas do Ocidente.		\r\n	', 'a ruptura das relações entre os Partidos Comunistas da URSS e da China (1959) consagrou a liderança política internacional russa submetendo a China a seus interesses e autoridades.		\r\n	', 'a chegada de Brejnev ao poder favoreceu o estouro de um movimento de reformas liberalizantes, que reestruturam o Estado Soviético extinguindo a censura interna e abrindo o país aos estrangeiros.		\r\n	'),
(14, 2, 'identifica as tensões internacionais durante a Revolução Russa.		\r\n	', 'ilustra as relações americano-soviéticas durante a Guerra Fria.		\r\n	', 'caracteriza o panorama mundial durante a Guerra do Golfo Pérsico.		\r\n	', 'revela o perigo da corrida armamentista durante a Revolução Chinesa.		\r\n	'),
(15, 2, 'atuar como o mais forte aliado da URSS naquela região.		\r\n	', 'ser a principal base de operações norte-americanas na Ásia.		\r\n	', 'competir com as forças econômicas alemãs e inglesas.		\r\n	', 'buscar o seu nível econômico de antes da Primeira Guerra Mundial.		\r\n	'),
(16, 5, 'à África do Sul.		\r\n	', 'à China.		\r\n	', 'à Índia.		\r\n	', 'ao Brasil.		\r\n	'),
(17, 2, 'localismo		\r\n	', 'nacionalismo		\r\n	', 'regionalismo		\r\n	', 'eurocentrismo		\r\n	'),
(18, 2, 'valorização do pan-americanismo frente à projeção da União Europeia		\r\n	', 'resistência de governos nacionalistas às pressões hegemônicas externas		\r\n	', 'criação de regiões de livre-comércio contrárias à globalização econômica		\r\n	', 'aplicação do protecionismo alfandegário à exportação de produtos primários		\r\n	'),
(19, 2, 'diminuição dos fluxos internacionais de capital		\r\n	', 'aumento do número de polos de poder mundial		\r\n	', 'redução das desigualdades sociais entre o Norte e o Sul		\r\n	', 'crescimento da probabilidade de conflitos entre países centrais e periféricos		\r\n	'),
(20, 1, 'A globalização neoliberal promove a livre circulação de capitais e mercadorias, mas fecha as fronteiras para a força de trabalho.		\r\n	', 'As propostas de civilização europeias destinadas aos imigrantes, em vigor durante o Século XX, estão sendo abolidas em frente às crises econômicas.		\r\n	', 'O ciclo migratório africano e mundial está em fase de esgotamento, pois a automação crescente das atividades econômicas não prevê mão de obra pouco qualificada.		\r\n	', 'Os acordos econômicos e diplomáticos entre os países de emigração e os de imigração têm sido postos em prática para diminuir a movimentação, principalmente de homens jovens.		\r\n	'),
(21, 4, 'É um grupo coeso em suas políticas econômicas internas, em que cada membro contribui financeiramente para um Fundo Monetário Internacional para salvaguardar os interesses das empresas multinacionais. Os países membros praticam uma ajuda humanitária aos países pobres vitimados por guerras civis, violências étnicas e catástrofes naturais, através de recursos do Fundo Monetário e de instituições financeiras privadas.		\r\n	', 'É uma aliança militar das nações capitalistas ocidentais mais desenvolvidas, formada para combater os países que constituem o “eixo do mal” e que disseminam o terrorismo internacional, que ameaçam a hegemonia das empresas capitalistas, a estabilidade política internacional e a soberania sobre as reservas energéticas mundiais.		\r\n	', 'É um fórum de discussões políticas e econômicas dos países que controlam a macroeconomia global, formado para combater a crise financeira mundial ocorrida no final de 2008. O G-20 forma um bloco político-econômico constituído por países com as mesmas características socioeconômicas, objetivando ampliar o ciclo de reprodução do capital em escala regional.		\r\n	', 'É um grupo de países, criado no final da década de 1990, com o objetivo de superar as sucessivas crises financeiras geradas pela economia global. Visa a favorecer a concertação internacional, integrando o princípio de um diálogo ampliado, levando em conta o peso econômico crescente dos países membros. O grupo reúne as 19 maiores economias do mundo mais a União Europeia, que juntas compreendem 85% do produto nacional bruto mundial, 80% do comércio mundial e dois terços da população mundial.		\r\n	'),
(22, 3, 'F, F, F, V e F.		\r\n	', 'F, V, F, F e F.		\r\n	', 'V, F, F, F e F.		\r\n	', 'F, F, V, F e F.		\r\n	'),
(23, 4, 'O processo de globalização, mesmo diante de vários contrastes econômicos e sociais, reflete na total difusão de informações e acesso indiferenciado a elas, reduzindo, quase que totalmente, as desigualdades sociais de forma homogênea.		\r\n	', 'A Internet em muito contribuiu para difusão de informações e acesso a serviços (e-mails, dados bancários, compra e venda de produtos, dentre outras atividades), mas em nada contribuiu para o redimensionamento das concepções de tempo e espaço, essenciais à dinâmica da globalização.		\r\n	', 'A globalização, cuja imagem reflete a estrutura econômica norte-americana, é também representada por instituições como o FMI e o Banco Mundial, nas quais o neoliberalismo, mesmo atuando para reduzir as barreiras aos fluxos globais, não viabiliza investimentos produtivos nem a ampliação do comércio em países subdesenvolvidos como o Brasil e o México.		\r\n	', 'A expansão do processo de globalização também se dá de forma “sutil” e, mesmo com difusão de informações e acesso a serviços, fortalecem grupos, países ou regiões, utilizando-se princípios de domínio sobre mercadorias, capitais, serviços, informações e pessoas.		\r\n	'),
(24, 3, 'V – V – V', 'V – F – V	\r\n	', 'F – V – F\r\n	', 'F – F – F\r\n		\r\n			\r\n	'),
(25, 3, 'I, II, III e IV.		\r\n	', 'I e IV, apenas.		\r\n	', 'I, II e III, apenas.		\r\n	', 'II, III e IV, apenas.		\r\n	'),
(26, 5, '“A luminosidade sorria no ar: exatamente isto. Era um suspiro do mundo.” (Clarice Lispector)		\r\n	', '“As palavras não nascem amarradas, elas saltam, se beijam, se dissolvem…” (Drummond)		\r\n	', '“Quando essa não-palavra morde a isca, alguma coisa se escreveu.” (Clarice Lispector)		\r\n	', '“A poesia vai à esquina comprar jornal”. (Ferreira Gullar)		\r\n	'),
(27, 3, 'Os tempos mudaram, no devagar depressa do tempo.		\r\n	', 'Última flor do Lácio, inculta e bela, és a um tempo esplendor e sepultura.		\r\n	', 'Apressadamente, todos embarcaram no trem.		\r\n	', 'Ó mar salgado, quanto do teu sal são lágrimas de Portugal.		\r\n	'),
(28, 1, 'Ao vencido, ódio ou compaixão, ao vencedor, as batatas.		\r\n	', 'A paz, nesse caso, é a destruição(…)		\r\n	', 'Daí a alegria da vitória, os hinos, as aclamações, recompensas públicas e todos os demais efeitos das ações bélicas.		\r\n	', '(…) mas, rigorosamente, não há morte(…)		\r\n	'),
(29, 2, '“A novidade veio dar à praia/na qualidade rara de sereia”		\r\n	', '“A novidade que seria um sonho/o milagre risonho da sereia/virava um pesadelo tão medonho”		\r\n	', '“A novidade era a guerra/entre o feliz poeta e o esfomeado”		\r\n	', '“Metade o busto de uma deusa maia/metade um grande rabo de baleia”		\r\n	'),
(30, 5, '“O meu olhar é nítido como um girassol” (Alberto Caeiro)		\r\n	', '“Meu amor me ensinou a ser simples como um largo de igreja” (Oswald de Andrade)		\r\n	', 'A casa dela é escura como a noite.		\r\n	', 'Ele é lerdo como uma lesma.		\r\n	'),
(31, 5, 'I, III, II.		\r\n	', 'I, IV, II.		\r\n	', 'II, III, II.		\r\n	', 'III, IV, II.		\r\n	'),
(32, 3, 'eufemismo		\r\n	', 'antítese		\r\n	', 'aliteração		\r\n	', 'silepse		\r\n	'),
(33, 1, 'retratado com objetividade, numa perspectiva rigorosa e científica.		\r\n	', 'idealizado sobre o pano de fundo da natureza, da qual é o herói épico.		\r\n	', 'pretexto episódico para descrição da natureza.		\r\n	', 'visto com o desprezo do branco preconceituoso, que o considera inferior.		\r\n	'),
(34, 4, 'Conde Lopo;		\r\n	', 'Macário;\r\n\r\n		\r\n	', 'espumas Flutuantes;		\r\n	', 'Noite na Taverna;\r\n\r\n		\r\n	'),
(35, 5, '2 - 3 - 2 - 1 - 2 - 1;\r\n		\r\n	', '1 - 3 - 2 - 1 - 2 - 3;		\r\n	', '3 - 2 - 2 - 1- 2 - 2;		\r\n	', '2 - 1 - 2 - 2 - 1 - 1;		\r\n	'),
(36, 5, '25%		\r\n	', '50%		\r\n	', '60%		\r\n	', '65%		\r\n	'),
(37, 4, '10%		\r\n	', '12%	\r\n	', '24%		\r\n	', '36%		\r\n	'),
(38, 2, 'R$1.188,00		\r\n	', 'R$1.200,00		\r\n	', 'R$1.220,00		\r\n	', 'R$1.310,00	\r\n	'),
(39, 1, '3		\r\n	', '1/3		\r\n	', '3/4		\r\n	', '1		\r\n	'),
(40, 4, '3000%.		\r\n	', '300%.		\r\n	', '900%		\r\n	', '9%.		\r\n	'),
(41, 5, '255,55		\r\n	', '215,62		\r\n	', '276,00		\r\n	', '313,63		\r\n	'),
(42, 4, '24		\r\n	', '18		\r\n	', '8		\r\n	', '10		\r\n	'),
(43, 1, '5%.		\r\n	', '10%.		\r\n	', '11%.		\r\n	', '19%.		\r\n	'),
(44, 3, 'R$ 400,00		\r\n	', 'R$ 500,00		\r\n	', 'R$ 600,00		\r\n	', 'R$ 700,00		\r\n	'),
(45, 1, '29,6%		\r\n	', '30,0%		\r\n	', '30,4%		\r\n	', '30,8%		\r\n	'),
(46, 3, '(PUC-RIO 2010)\r\n\r\nUma quantidade de água líquida de massa m = 200 g, a uma temperatura de 30 Cº, é colocada em uma calorímetro junto a 150 g de gelo a 0 Cº. Após atingir o equilíbrio, dado que o calor específico da água é c = 1,0 cal/(g . Cº) e o calor latente de fusão do gelo é L = 80 cal/g, calcule a temperatura final da mistura gelo + água.		\r\n	', '15 Cº		\r\n	', '0°C		\r\n	', '30 Cº		\r\n	'),
(47, 5, '300 J		\r\n	', '450 J		\r\n	', '750 J		\r\n	', '1750 J		\r\n	'),
(48, 3, '1060 J		\r\n	', '1567 J		\r\n	', '1680 J		\r\n	', '1867 J		\r\n	'),
(49, 2, 'a capacidade térmica do tabuleiro é maior que a do bolo.		\r\n	', 'a transferência de calor entre o tabuleiro e a mão é mais rápida que entre o bolo e a mão.		\r\n	', 'o bolo esfria mais rapidamente que o tabuleiro, depois de os dois serem retirados do forno.		\r\n	', 'o tabuleiro retém mais calor que o bolo.		\r\n	'),
(50, 2, '31,4A		\r\n	', '10,0A		\r\n	', '62,8A		\r\n	', '20,0A		\r\n	'),
(51, 4, '(UFU-MG)\r\n\r\nO átomo é a menor partícula que identifica um elemento químico. Ele possui duas partes, a saber: uma delas é o núcleo, constituído por prótons e nêutrons, e a outra é a região externa – a eletrosfera-, por onde circulam os elétrons. Alguns experimentos permitiram a descoberta das características das partículas constituintes do átomo.\r\n\r\nEm relação a essas características, indique a alternativa correta.		\r\n	', 'entre as partículas atômicas, os elétrons têm maior massa e ocupam maior volume no átomo.		\r\n	', 'entre as partículas atômicas, os prótons e os nêutrons têm maior massa e ocupam maior volume no átomo.		\r\n	', 'entre as partículas atômicas, os prótons e os nêutrons têm mais massa, mas ocupam um volume muito pequeno em relação ao volume total do átomo.		\r\n	'),
(52, 3, '641		\r\n	', '528		\r\n	', '623		\r\n	', '465		\r\n	'),
(53, 3, 'isóbaros		\r\n	', 'isótonos		\r\n	', 'isótopos		\r\n	', 'isótopos		\r\n	'),
(54, 2, ' I, III e V		\r\n	', 'I, IV e V		\r\n	', 'II e III		\r\n	', 'II, III e V		\r\n	'),
(55, 1, 'o íon fluoreto F-.		\r\n	', 'o átomo de sódio Na.		\r\n	', 'o íon cálcio Ca2+		\r\n	', 'o íon sulfeto S2-		\r\n	'),
(56, 3, 'II e IV, apenas. 		\r\n	', 'II e III, apenas.		\r\n	', 'I e III, apenas.\r\n		\r\n	', 'I e IV, apenas.\r\n		\r\n	'),
(57, 5, 'Capacidade de impor a própria vontade dentro de uma relação social.\r\n		\r\n	', 'Capacidade de liderar numa determinada situação social.\r\n		\r\n	', 'Probabilidade de impor a sua vontade numa determinada situação social.\r\n		\r\n	', 'Probabilidade de operar através de atos ou uso da violência.\r\n		\r\n	'),
(58, 4, 'Homogeneização dos mercados, tecnologias informacionais e estatização.\r\n		\r\n	', 'Exportação de mercadorias, competição global e economia planificada.\r\n		\r\n	', '\r\nc)Tecnologias informacionais, competições e monopólios públicos.\r\n		\r\n	', 'Competição, colaboração entre Estados imperiais e tecnologias informacionais.\r\n		\r\n	'),
(59, 2, 'socialismo científico.\r\n		\r\n	', 'materialismo histórico.\r\n		\r\n	', 'racionalismo cartesiano.\r\n		\r\n	', 'fenomenologia do espírito.\r\n		\r\n	'),
(60, 2, 'a Revolução dos cravos em Portugal e a Revolução Moçambicana.\r\n		\r\n	', 'a Revolução Industrial e a Revolução Francesa.\r\n		\r\n	', 'a Revolução Russa e a Revolução Chinesa.\r\n		\r\n	', 'a Revolução Mexicana e a Revolução Nicaragüense.\r\n		\r\n	'),
(61, 3, 'caos social.\r\n		\r\n	', 'realidade social.\r\n		\r\n	', 'fato social.\r\n		\r\n	', 'arrogância social.		\r\n	'),
(62, 1, '3, 1, 2\r\n		\r\n	', '2, 3, 1\r\n		\r\n	', '1, 2, 3\r\n		\r\n	', '2, 1, 3\r\n		\r\n	'),
(63, 3, 'tirania.\r\n		\r\n	', 'plutocracia.\r\n		\r\n	', 'cidadania.\r\n		\r\n	', 'bonapartismo.\r\n		\r\n	'),
(64, 3, 'a secessão, pela qual a minoria discriminada obteria a igualdade de direitos na condição da sua concentração espacial, num tipo de independência nacional.\r\n		\r\n	', 'a reunificação da sociedade que se encontra fragmetada em grupos de diferentes comunidades étnicas, confissões religiosas e formas de vida, em torno da coesão de uma cultura política nacional. 		\r\n	', 'a coexistência das diferenças, considerando a possibilidade de os discursos de autoentendimento se submeterem ao debate público, cientes de que estarão vinculados à coerção do melhor argumento.		\r\n	', 'a autonomia dos indivíduos que, ao chegarem à vida adulta, tenham condições de se libertar das tradições de suas origens em nome da harmonia da política nacional. 		\r\n	'),
(65, 2, 'o crescimento da carga tributária.		\r\n	', '\r\n\r\no aumento da mobilidade ocupacional. 		\r\n	', 'a redução da competitividade entre as empresas. 		\r\n	', 'o direcionamento das vendas para os mercados regionais.		\r\n	'),
(66, 5, '\r\n\r\ndefendem os sentidos como critério originário para considerar um conhecimento legítimo. 		\r\n	', '\r\n\r\nentendem que é desnecessário suspeitar do significado de uma ideia na reflexão filosófica e crítica. 		\r\n	', 'são legítimos representantes do criticismo quanto à gênese do conhecimento.		\r\n	', 'concordam que conhecimento humano é impossível em relação às ideias e aos sentidos.		\r\n	'),
(67, 4, 'eram baseadas nas ciências da natureza. 		\r\n	', 'refutavam as teorias de filósofos da religião. 		\r\n	', 'tinham origem nos mitos das civilizações antigas. 		\r\n	', 'postulavam um princípio originário para o mundo.		\r\n	'),
(68, 4, 'Estabelecendo um abismo intransponível entre as duas. \r\n	', 'Privilegiando os sentidos e subordinando o conhecimento a eles. 		\r\n	', 'Atendo-se à posição de Parmênides de que razão e sensação são inseparáveis. 		\r\n	', 'Afirmando que a razão é capaz de gerar conhecimento, mas a sensação não.		\r\n	'),
(69, 1, 'a reivindicação de autonomia da capacidade racional como expressão da maioridade. 		\r\n	', 'o exercício da racionalidade como pressuposto menor diante das verdades eternas. 		\r\n	', 'a imposição de verdades matemáticas, com caráter objetivo, de forma heterônoma. 		\r\n	', 'a compreensão de verdades religiosas que libertam o homem da falta de entendimento. 		\r\n	'),
(70, 1, '\r\n\r\ninstrumentalização e mercantilização da fé religiosa. 		\r\n	', '\r\n\r\ncrítica religiosa à massificação de produtos de consumo. 		\r\n	', 'recuperação das práticas religiosas tradicionais.		\r\n	', 'indiferença das igrejas e religiões frente às demandas de mercado. 		\r\n	'),
(71, 2, 'as diferenças sociais de gênero. 		\r\n	', 'o determinismo biológico. 		\r\n	', 'os fatores de natureza histórica.		\r\n	', 'os determinismos materiais da sociedade.		\r\n	'),
(72, 5, 'a supremacia de tendências estatais de controle sobre a economia liberal. 		\r\n	', 'o aumento do nível de pobreza nos países subdesenvolvidos. 		\r\n	', 'a hegemonia do planejamento familiar nos países do Terceiro Mundo.		\r\n	', 'o declínio dos valores morais e religiosos na era contemporânea.		\r\n	'),
(73, 3, 'influências religiosas e metafísicas são o principal veículo no processo evolutivo humano ao longo do tempo. 		\r\n	', 'são os condicionamentos psicológicos que infuenciam de maneira decisiva o progresso na história. 		\r\n	', 'a sobrevivência da espécie humana ao longo da história é explicada pela primazia de fatores de natureza evolutiva. 		\r\n	', 'os fatores econômicos e materiais são os principais responsáveis pelas transformações históricas.		\r\n	'),
(74, 4, 'está inserido em um processo de resistência ao poder disciplinar na escola. 		\r\n	', 'é fruto de uma ação do Estado para incrementar o grau de liberdade nas escolas. 		\r\n	', 'indica a consolidação de mecanismos de consulta democrática na escola pública. 		\r\n	', 'introduz novas formas institucionais de controle sobre a liberdade individual.\r\n		\r\n	'),
(75, 4, 'uma tendência filosófica especificamente europeia e ocidental de crítica cultural e religiosa. 		\r\n	', 'uma tendência oposta a diversas formas de desenvolvimento da autonomia individual. 		\r\n	', 'um conjunto de princípios morais absolutos, dotados de fundamentação teológica e cristã.		\r\n	', 'um movimento amplo de propagação da crítica racional a diversas formas de preconceito.		\r\n	'),
(78, 2, 'q = 0°', 'q = 30°		\r\n	', 'q = 45°		\r\n	', 'q = 60°		\r\n	'),
(79, 5, 'tem o mesmo sentido da corrente elétrica.		\r\n	', 'é uniforme.		\r\n	', 'é paralelo ao fio.		\r\n	', 'aponta para o fio.		\r\n	'),
(80, 4, 'o polo norte do imã.', 'o polo sul do imã .', ' fora do imã.		\r\n	', 'dentro do imã.		\r\n	'),
(81, 5, 'uma arruela de ferro.		\r\n	', 'um prego.		\r\n	', 'uma lâmina de barbear.		\r\n	', 'uma panela de ferro.		\r\n	'),
(82, 2, ' 1 e 2		\r\n	', '1 e 3		\r\n	', '2 e 3		\r\n	', '2 e 4		\r\n	'),
(83, 3, 'a força magnética terá a mesma direção do campo magnético.		\r\n	', 'a força magnética fará com que a energia cinética da partícula aumente.		\r\n	', 'R.F = 2.K.		\r\n	', 'o trabalho da força magnética será negativo.		\r\n	'),
(84, 1, ' aparece uma corrente elétrica induzida na espira, que gera um campo magnético que se opõe a essa rotação.		\r\n	', 'aparece uma corrente elétrica induzida na espira, que gera um campo magnético que favorece essa rotação.		\r\n	', ' aparece uma corrente elétrica oscilante induzida na espira, que gera um campo magnético oscilante.		\r\n	', 'aparecem correntes elétricas induzidas de sentidos opostos em ladosopostos da espira que, por isso, não geram campo magnético.		\r\n	'),
(85, 1, 'a afirmativa I é verdadeira.		\r\n	', ' a afirmativa II é verdadeira.		\r\n	', 'a afirmativa III é verdadeira.		\r\n	', 'todas as afirmativas são falsas		\r\n	'),
(86, 5, '1		\r\n	', '2		\r\n	', '3		\r\n	', '4		\r\n	'),
(87, 5, 'só A.		\r\n	', 'só B.		\r\n	', 'só C.		\r\n	', 'A e B.		\r\n	'),
(88, 2, 'retratado com objetividade, numa perspectiva rigorosa e científica.		\r\n	', 'idealizado sobre o pano de fundo da natureza, da qual é o herói épico.		\r\n	', 'pretexto episódico para descrição da natureza.		\r\n	', 'visto com o desprezo do branco preconceituoso, que o considera inferior.\r\n\r\n		\r\n	'),
(89, 1, 'ponha em dúvida o significado aparente da realidade, muitas vezes enganoso.		\r\n	', 'interfira emocionalmente no texto, tornando-o dramático, sentimentalista e ultra-romântico.		\r\n	', 'busque revelar a profunda hipocrisia e bondade que, a um tempo, caracterizam o comportamento dos seres humanos.		\r\n	', 'busque revelar o aspecto mais piedoso do caráter das personagens construindo uma narrativa eminentemente moralista.		\r\n	'),
(90, 4, 'clássica		\r\n	', 'barroca		\r\n	', 'arcádica		\r\n	', 'naturalista		\r\n	'),
(91, 5, 'naturalismo e o realismo, a fim de evidenciarem as mazelas do tempo, deram ênfase à análise do comportamento psicológico.		\r\n	', 'a prosa romântica pautou-se por uma visão mecanicista do homem e das relações humanas.		\r\n	', 'realismo caracterizou a realidade por meio da metáfora elegante, da ironia, de um cinismo penetrante e refinado.		\r\n	', 'romantismo, incorporando elementos populares e prosaicos, idealizou a força física e a pujança moral do povo.		\r\n	'),
(92, 3, 'teocentrismo, hipersensibilidade, alegria, otimismo e crença.		\r\n	', 'etnocentrismo, insensibilidade, descontração, otimismo e crença na sociedade.		\r\n	', 'egocentrismo, hipersensibilidade, melancolia, pessimismo, angústia e desespero.\r\n		\r\n	', 'teocentrismo, insensibilidade, descontração, angústia e desesperança.		\r\n	'),
(93, 1, 'Barroco – Arcadismo – Romantismo.\r\n		\r\n	', 'Barroco – Romantismo – Parnasianismo.		\r\n	', 'Romantismo – Parnasianismo – Simbolismo.		\r\n	', 'Romantismo – Simbolismo – Modernismo.		\r\n	'),
(94, 5, 'Portugal, de Miguel Torga.\r\n\r\n		\r\n	', 'Quincas Borba, de Machado de Assis.		\r\n	', 'Os maias, de Eça de Queirós.		\r\n	', 'Vidas secas, de Graciliano Ramos.		\r\n	'),
(95, 4, 'Camilo Castelo Branco e José de Alencar.		\r\n	', 'Machado de Assis e Miguel Torga.		\r\n	', 'Gil Vicente e Nelson Rodrigues.		\r\n	', 'Gil Vicente e Martins Pena.		\r\n	'),
(96, 1, 'apego ao equilíbrio na forma de expressão; presença do nacionalismo, pela temática indianista e pela valorização da natureza brasileira.		\r\n	', 'resistência aos exageros sentimentais e à forma de expressão subordinada às emoções; visão da poesia a serviço de causas sociais, como a escravidão.\r\n		\r\n	', 'expressão preocupada com o senso de medida; "mal do século"; natureza como amiga e confidente.		\r\n	', 'transbordamento na forma de expressão; valorização do índio como típico homem nacional; apresentação da natureza como refúgio dos males do coração.\r\n		\r\n	'),
(97, 4, '"(...) esse laguinho e essa saudade da valsa de Ouro Preto".		\r\n	', '"Ah, como pisavam de leve na areia, com força em nossos corações!"\r\n\r\n		\r\n	', '"Na alameda elegante, moças desfilavam perante os rapazes, às quintas e domingos".		\r\n	', '"(...) fontes bem luminosas na escuridão, e bem musicais em meio à cacofonia geral".		\r\n	'),
(98, 2, '6 km', '6.200 m', '11.200 m\r\n	', '4 km'),
(99, 5, '2100 km		\r\n	', '1020 km		\r\n	', '1120 km', '1210 km		\r\n	'),
(100, 4, '86,2%.		\r\n	', '96,2%.		\r\n	', '97,2%.		\r\n	', '99,6%.		\r\n	'),
(101, 3, 'R$ 4 222,22.		\r\n	', 'R$ 4 523,80		\r\n	', 'R$ 5 000,00.		\r\n	', 'R$ 13 300,00.		\r\n	'),
(102, 2, '16%		\r\n	', '24%.		\r\n	', '32%.		\r\n	', '48%.		\r\n	'),
(103, 4, 'a grande extensão de asfaltos e cimentos em áreas urbanas, além de reter o calor, regulariza as temperaturas e minimiza a formação de ilhas de calor.		\r\n	', 'a poluição de resíduos industriais e esgotos, nos mananciais hídricos, pouco influencia na qualidade e na quantidade de água para o consumo humano.		\r\n	', 'a presença da poluição atmosférica gerada pelas indústrias e veículos motorizados é responsável por inúmeros problemas de saúde como alergias, doenças respiratórias, entre outros.		\r\n	', 'o aumento da liberação de gás carbônico por indústrias, veículos e agropecuária é responsável pelo desaparecimento do fenômeno natural conhecido como efeito estufa.		\r\n	'),
(104, 4, 'Estão incorretas as afirmativas I, III e V.		\r\n	', 'Estão incorretas as afirmativas II, IV.		\r\n	', 'Estão incorretas as alternativas I, IV e V.		\r\n	', 'Apenas a afirmativa III está incorreta.		\r\n	'),
(105, 4, 'radiação de ondas longas.		\r\n	', 'conveção solar.		\r\n	', 'advecção solar.		\r\n	', 'radiação de ondas curtas.		\r\n	'),
(106, 4, 'Durante o inverno, em Curitiba, é comum a ação da Massa Polar Atlântica, que facilita a ocorrência de problemas respiratórios, poisa) aumenta a umidade relativa do ar e promove a inversão térmica, o que provoca a concentração de poluentes nas partes altas da cidade. \r\n	', 'aumenta a umidade relativa do ar e promove a inversão térmica, o que provoca a concentração de poluentes próximo da superfície do solo. ', 'reduz a umidade relativa do ar e promove um maior aquecimento da parte central da cidade, se comparado à periferia, o que concentra os poluentes. ', 'reduz a umidade relativa do ar e promove a inversão térmica, o que provoca a concentração de poluentes próximos da superfície do solo. '),
(107, 3, 'efeito estufa.		\r\n	', 'ilhas de calor.		\r\n	', 'inversão térmica.		\r\n	', 'chuva ácida.		\r\n	');

-- --------------------------------------------------------

--
-- Estrutura da tabela `questions`
--

CREATE TABLE `questions` (
  `id` int(4) NOT NULL,
  `disciplineId` int(2) NOT NULL,
  `difficulty` int(1) NOT NULL,
  `question` varchar(1500) NOT NULL,
  `value` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `questions`
--

INSERT INTO `questions` (`id`, `disciplineId`, `difficulty`, `question`, `value`) VALUES
(1, 3, 3, 'Cesgranrio) A URSS transformou-se, após 1945, numa das potências mundiais, tanto no campo econômico como técnico. Um dos melhores exemplos dessa transformação é o:', 60),
(2, 3, 2, '(Cesgranrio) No início da década de 60, o arsenal nuclear à disposição das grandes potências era suficiente para destruir a humanidade, caso fosse utilizado em uma situação de confronto. Ao assumir o governo, o Presidente Kennedy (1961-63) defendeu a substituição da política externa norte-americana de confronto por uma de entendimento com a URSS, cujo objetivo era o desarmamento gradual das duas superpotências.  Esse programa do governo Kennedy foi conhecido como:', 40),
(3, 3, 3, '(Cesgranrio) Ao final da Segunda Guerra Mundial, a ruptura do acordo que unira os aliados vitoriosos gerou um ordenamento político internacional baseado na bipolaridade. Nesse contexto, crises políticas e tensões sociais desencadearam um processo de construção do socialismo em diversos países. Assinale a opção que apresenta uma afirmativa correta sobre a construção do socialismo no mundo do pós-guerra:', 60),
(4, 3, 4, '(Cesgranrio) O fim da Guerra Fria, expresso na extinção da União Soviética, em 1991, acarretou um novo equilíbrio e o ordenamento das relações internacionais, que se caracteriza por um (a):', 80),
(5, 3, 1, '(Cesgranrio) Após a Segunda Guerra Mundial, consolidou-se uma ordem político-econômica internacional que expressou o(a):', 40),
(6, 3, 3, '(Faap) Após a Segunda Guerra Mundial, a URSS estruturou um plano de cooperação política com os países do bloco oriental, criado, em 1947:', 60),
(7, 3, 2, '(Fatec) "É lógico que os EUA devem fazer o que lhes for possível para ajudar a promover o retorno ao poder econômico normal no mundo, sem o que não pode haver estabilidade política nem garantia de paz."\r\n                (Plano Marshall 5. VI. 1947)\r\nEsse plano', 40),
(8, 3, 5, '(Fgv) Em junho de 1947, o governo dos EUA passou a implementar um projeto de reconstrução da Europa denominado Plano Marshall. Qual dos tópicos a seguir NÃO é uma causa desse plano:', 80),
(9, 3, 4, 'Os 45 anos que vão do lançamento das bombas atômicas até o fim da União Soviética, não foram um período homogêneo único na história do mundo. (...) dividem-se em duas metades, tendo como divisor de águas o início da década de 70. Apesar disso, a história deste período foi reunida sob um padrão único pela situação internacional peculiar que o dominou até a queda da URSS.\r\n(HOBSBAWM, Eric J. Era dos Extremos. São Paulo: Cia das Letras,1996)\r\n\r\nO período citado no texto e conhecido por “Guerra Fria” pode ser definido como aquele momento histórico em que houve', 60),
(10, 3, 1, '(Mackenzie)\r\nI- "A OTAN, Organização do Tratado do Atlântico Norte, vai começar sua expansão para o Leste Europeu até junho de 1997.\r\nA afirmação foi feita à Folha (...) pelo secretário-geral da entidade (...) e se refere à data na qual ele pretende que seja feito o convite oficial a novos membros para a Aliança Militar (...)\r\nOs parceiros (...) sairão da Parceria para a Paz, acordo militar entre 27 países da OTAN, Leste Europeu e Ásia, lançado em 1994. A Polônia é favorita."\r\n                ("Folha de São Paulo")\r\n\r\nII- "Mais de 900 militares americanos (...) foram mantidos como prisioneiros na Coréia do Norte, após o fim da Guerra da Coréia (...) muitos dos prisioneiros foram submetidos a experiências com drogas e depois executados.\r\nAs experiências, para determinar a ação das drogas em interrogatórios, foram conduzidas por agentes Tchecoslovácos e Soviéticos."\r\n                ("O Estado de São Paulo")\r\n\r\nIII- "O Vaticano não comentou ontem, alegações de que o Papa João Paulo II e o governo dos E.U.A. (CIA), trabalhavam juntos em segredo na década de 80, para apressar o fim do comunismo na Polônia.\r\nA aliança informal entre os E.U.A. e o Vaticano inclui corte de verbas do Governo Norte-Americano para programas de controle de natalidade no país e o silêncio do Papa quanto à instalação de mísseis na Europa Ocidental."\r\n            ("Folha de São Paulo")\r\n\r\nDentre os textos anteriores, relacionam-se com a Guerra Fria:', 40),
(11, 3, 2, '(Puccamp) "...inspirado por razões humanitárias e pela vontade de defender uma certa concepção de vida ameaçada pelo comunismo, constitui também o meio mais eficaz de alargar e consolidar a influência norte-americana no mundo, um dos maiores instrumentos de sua expansão (...) tem por conseqüência imediata consolidar os dois blocos e aprofundar o abismo que separava o mundo comunista e o Ocidente..."\r\n\r\n"...as partes estão de acordo em que um ataque armado contra uma ou mais delas na Europa ou na América do Norte deve ser considerado uma agressão contra todas; e, conseqüentemente, concordam que, se tal agressão ocorrer, cada uma delas (...) auxiliará a parte ou as partes assim agredidas (...)"\r\n\r\nOs textos identificam, respectivamente,', 60),
(12, 3, 3, '(Puccamp) "A bipolarização do mundo, após a Segunda Guerra Mundial, apesar de ter se constituído na principal referência para as relações internacionais, não chegou a garantir um verdadeiro equilíbrio mundial. Nesse contexto consolidou-se a hegemonia internacional norte-americana".  A esse respeito pode-se afirmar que na presidência de', 60),
(13, 3, 3, '(Puccamp) "A construção de uma nova ordem mundial, após a Segunda Guerra Mundial, contou com a participação da União Soviética, cuja importância estendeu-se até sua desintegração em 1991".\r\nSobre o período mencionado no texto, pode-se afirmar corretamente que		\r\n	', 60),
(14, 3, 4, '(Puccamp) "... foi um período em que a guerra era improvável, mas a paz era impossível. A paz era impossível porque não havia maneira de conciliar os interesses de capitalistas e comunistas. Um sistema só poderia sobreviver à custa da destruição total do outro. E a guerra era improvável porque os dois blocos tinham acumulado tamanho poder de destruição, que se acontecesse um conflito generalizado seria, com certeza, o último..."\r\n\r\nO texto descreve uma problemática que, na história recente da humanidade,		\r\n	', 80),
(15, 3, 1, '(Uel) As mudanças no panorama internacional representadas pela vitória socialista de Mao-Tsé-tung na China, pela eclosão da Guerra da Coréia e pelas crescentes dificuldades no relacionamento com a URSS, repercutiram na forma de tratamento dispensada pelos Estados Unidos ao Japão.  Este, de "inimigo vencido", passou a		\r\n	', 40),
(16, 4, 3, '(UNIT/SE) - Universidade Tiradentes -\r\n“Bric de barro” mostra sua fragilidade.\r\nCom economia excessivamente dependente de um só produto de exportação e um parque industrial deteriorado, o país enfrenta o desafio do crescimento.\r\n(O Estado de São Paulo, 18/04/2010. p B11)\r\nCom base nos conhecimentos sobre as características dos países que compõem o Bric, pode-se concluir que o texto do jornal refere-se		\r\n	', 60),
(17, 4, 1, '(UERJ) - Universidade do Estado do Rio de Janeiro -\r\nNo admirável mundo novo das oportunidades fugazes e das seguranças frágeis, a sabedoria popular foi rápida em perceber os novos requisitos. Em 1994, um cartaz espalhado pelas ruas de Berlim ridicularizava a lealdade a estruturas que não eram mais capazes de conter as realidades do mundo: “Seu Cristo é judeu. Seu carro é japonês. Sua pizza é italiana. Sua democracia, grega. Seu café, brasileiro. Seu feriado, turco. Seus algarismos, arábicos. Suas letras, latinas. Só o seu vizinho é estrangeiro”.\r\nZygmunT Bauman Adaptado de Identidade. Rio de Janeiro: Zahar, 2005.\r\nA alteração de valores culturais em diversas sociedades é um dos efeitos da globalização da economia.\r\nO cartaz citado no texto ironiza uma referência cultural que pode ser associada ao conceito de:		\r\n	', 40),
(18, 4, 2, '(UERJ) - Universidade do Estado do Rio de Janeiro -\r\nA Cúpula das Américas surgiu em 1994, por iniciativa norte-americana. Os EUA criticavam a OEA (Organização dos Estados Americanos), que reúne todos os 34 países do hemisfério, exceto Cuba, e desejavam implantar a ALCA (Área de Livre Comércio das Américas).\r\nExercitando o papel de líder dos países da ALBA (Alternativa Bolivariana para os Povos de Nossa América), Hugo Chávez prometeu que “até as pedras falarão”, na quinta reunião da Cúpula das Américas, contra o bloqueio americano a Cuba e a favor de sua reincorporação à OEA. Criada em 2004, a ALBA é formada por Bolívia, Honduras, Venezuela, Dominica e Cuba.\r\nAdaptado de Folha de São Paulo, 12/04/2009\r\nAs divergências entre a ALBA e a OEA refletem mudanças nas relações entre os países americanos na atualidade.\r\nDe acordo com a notícia, essas mudanças se vinculam ao seguinte contexto político:		\r\n	', 60),
(19, 4, 3, '(UERJ) - Universidade do Estado do Rio de Janeiro -\r\nG-20 adota linha dura para combater crise\r\nGrupo anuncia maior controle para o sistema financeiro. Cercada de expectativas, a reunião do G-20, grupo que congrega os países mais ricos e os principais emergentes do mundo, chegou ao fim, em Londres, com o consenso da necessidade de combate aos paraísos fiscais e da criação de novas regras de fiscalização para o sistema financeiro. Além disso, os líderes concordaram, dentre várias medidas, em injetar US$ 1,1 trilhão na economia para debelar a crise.\r\nAdaptado de http://zerohora.clicrbs.com.br\r\nA passagem da década de 1980 para a de 1990 ficou marcada como um momento histórico no qual se esgotou um arranjo geopolítico e teve início uma nova ordem política internacional, cuja configuração mais clara ainda está em andamento.\r\nConforme se observa na notícia, essa nova geopolítica possui a seguinte característica marcante:		\r\n	', 80),
(20, 4, 4, '(EMESCAM/ES) - Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória -\r\nJá se tornou rotina a leitura de notícias sobre a travessia, em barcos toscos e frágeis de africanos que tentam vencer o Mediterrâneo e chegar às terras europeias. Os que sobrevivem, em geral, são presos e obrigados a fazer o caminho de volta. A Europa não quer mais imigrantes.\r\nSobre o conteúdo do texto, é correto afirmar que:		\r\n	', 80),
(21, 4, 5, '(UFMS) - Universidade Federal de Mato Grosso do Sul -\r\nQuestão 19:\r\nSobre o Grupo dos 20 ou G-20, assinale a alternativa correta.		\r\n	', 80),
(22, 4, 2, '(UFPI) - Universidade Federal do Piauí -\r\nNa última década do século XX, entra em cena uma nova ordem mundial, caracterizada pela multipolaridade. Essa característica é atribuída à(ao):		\r\nI. ( ) equilíbrio econômico entre Estados Unidos da América, União Europeia e Bacia do Pacífico.\r\nII. ( ) aumento do comércio internacional entre países do hemisfério Sul.\r\nIII. ( ) fortalecimento da democracia nos países asiáticos.\r\nIV. ( ) queda do muro de Berlim.\r\nV. ( ) fortalecimento da União Europeia.\r\nAssinale a alternativa correta:	', 40),
(23, 4, 3, '(UECE) - Universidade Estadual do Ceará -\r\nSobre o processo de globalização, assinale o correto.		\r\n	', 40),
(24, 4, 3, '(UCS/RS) - Universidade de Caxias do Sul -\r\nA globalização econômica independe de fronteiras nacionais. Com ela vieram o acirramento da concorrência e a consequente necessidade de proteção de mercados, que conduziram à formação de blocos econômicos, entre eles, os megablocos regionais, que também produzem uma geoeconomia planetária.\r\nAnalise a veracidade (V) ou falsidade (F) das proposições abaixo, considerando as características gerais dos blocos econômicos.\r\n( ) Em 1980 foi elaborado o Plano Schumam, que mudou o nome da Comunidade Econômica Europeia (CEE) para União Europeia (UE) e estabeleceu a moeda única (euro), a unificação das taxas e uma política monetária comum.\r\n( ) Na Conferência de Seattle, decidiu-se que a Apec (Cooperação Econômica da Ásia e do Pacífico) assumiria características de um bloco econômico regional, para que se criasse, até 2010, uma zona de livre comércio.\r\n( ) A COMESA (Mercado Comum do Sudeste Asiático) foi criada em 1992, com o objetivo de implantar uma zona de livre comércio e dar continuidade às ZEEs (Zonas Econômicas Especiais) do Sudeste Asiático.\r\nAssinale a alternativa que preenche corretamente os parênteses, de cima para baixo.		\r\n	', 40),
(25, 4, 4, '(UNIR/RO) - Fundação Universidade Federal de Rondônia -\r\nSobre a Organização das Nações Unidas (ONU) e seu símbolo, analise as afirmativas.\r\nI - Surgiu no fim da Segunda Guerra Mundial e sua sede fica em Nova Iorque.\r\nII - Tem por objetivo preservar a paz e a segurança mundial.\r\nIII - Possui várias agências que atuam em vários setores como o PNUD, a FAO entre outros.\r\nIV - O símbolo da ONU é uma projeção conforme que distorce a forma, mas mantém o tamanho real dos países.\r\nEstão corretas as afirmativas		\r\n	', 40),
(26, 1, 1, '(UFPE) Assinale a alternativa em que o autor NÃO utiliza prosopopéia.		\r\n	', 40),
(27, 1, 2, '(FUVEST) A catacrese, figura que se observa na frase “Montou o cavalo no burro bravo”, ocorre em:\r\n		\r\n	', 40),
(28, 1, 1, '(UFF) TEXTO\r\n\r\nNão há morte. O encontro de duasexpansões, ou a expansão de duas formas, pode determinar a supressão deduas formas, pode determinar a supressão de uma delas; mas,rigorosamente, não há morte, há vida, porque a supressão de uma é acondição da sobrevivência da outra, e a destruição não atinge oprincípio universal e comum. Daí o caráter conservador e benéfico daguerra.\r\n\r\nSupõe tu um campo de batatas e duastribos famintas. As batatas apenas chegam para alimentar uma dastribos, que assim adquire forças para transpor a montanha e ir à outravertente, onde há batatas em abundância; mas, se as duas tribosdividirem em paz as batatas do campo, não chegam a nutrir-sesuficientemente e morrem de inanição. A paz, nesse caso, é adestruição; a guerra é a conservação. Uma das tribos extermina a outrae recolhe os despojos. Daí a alegria da vitória, os hinos, aclamações,recompensas públicas e todos os demais efeitos das ações bélicas. Se aguerra não fosse isso, tais demonstrações não chegariam a dar-se, pelomotivo real de que o homem só comemora e ama o que lhe é aprazível ouvantajoso, e pelo motivo racional de que nenhuma pessoa canoniza umaação que virtualmente a destrói. Ao vencido, ódio ou compaixão; aovencedor, as batatas.\r\n\r\n(ASSIS, Machado fr. Quincas Borba. Rio de Janeiro, Civilização Brasileira/INL, 1976.)\r\n\r\nAssinale dentre as alternativas abaixo, aquela em que o uso da vírgula marca a supressão (elipse) do verbo:		\r\n	', 40),
(29, 1, 2, '(ANHEMBI)\r\n\r\n“A novidade veio dar à praia\r\n\r\nna qualidade rara de sereia\r\n\r\nmetade um busto de uma deusa maia\r\n\r\nmetade um grande rabo de baleia\r\n\r\na novidade era o máximo\r\n\r\ndo paradoxo estendido na areia\r\n\r\nalguns a desejar seus beijos de deusa\r\n\r\noutros a desejar seu rabo pra ceia\r\n\r\noh, mundo tão desigual\r\n\r\ntudo tão desigual\r\n\r\nde um lado este carnaval\r\n\r\ndo outro a fome total\r\n\r\ne a novidade que seria um sonho\r\n\r\nmilagre risonho da sereia\r\n\r\nvirava um pesadelo tão medonho\r\n\r\nali naquela praia, ali na areia\r\n\r\na novidade era a guerra\r\n\r\nentre o feliz poeta e o esfomeado\r\n\r\nestraçalhando uma sereia bonita\r\n\r\ndespedaçando o sonho pra cada lado”\r\n\r\n(Gilberto Gil – A Novidade)\r\n\r\nAssinale a alternativa que ilustre a Figura de Linguagem descrita na questão anterior:		\r\n	', 40),
(30, 1, 1, '(ANHEMBI) Tenho fases\r\n\r\nFases de andar escondida,\r\n\r\nfases de vir para a rua…\r\n\r\nPerdição da minha vida!\r\n\r\nPerdição da vida minha!\r\n\r\nTenho fases de ser tua,\r\n\r\ntenho outras de ser sozinha.\r\n\r\nFases que vão e que vêm,\r\n\r\nno secreto calendário\r\n\r\nque um astrólogo arbitrário\r\n\r\ninventou para meu uso.\r\n\r\nE roda a melancolia\r\n\r\nseu interminável fuso!\r\n\r\nNão encontro com ninguém\r\n\r\n(tenho fases, como a lua…)\r\n\r\nNo dia de alguém ser meu\r\n\r\nnão é dia de eu ser sua…\r\n\r\nE, quando chega esse dia,\r\n\r\noutro desapareceu…\r\n\r\n(Lua Adversa – Cecília Meireles)\r\n\r\nIndique a alternativa que não contenha a mesma figura de linguagem presente nesse verso do poema:		\r\n	', 80),
(31, 1, 2, '(UFPB) Um dia,o Simão me chamou: – “Vem ver. Olha ali”. Era uma mulher, atarracada,descalçada, que subia o caminho do morro. (Diante do Sanatorinho haviaum morro. Os doentes em bom estado podiam ir até lá em cima, pela manhãe à tarde.) Lembro-me de que, de repente, a mulher parou e acenou parao Sanatorinho. Não sei quantas janelas retribuíram. E o curioso é que,desde o primeiro momento, Simão saltou: – “É minha! Vi primeiro!”.\r\n\r\nUns oitenta doentes tinham visto, aomesmo tempo. Mas o Simão era um assassino. Como ele próprio dizia, semódio, quase com ternura, “matei um”. E o crime pretérito intimidava osdemais. Constava que trouxera, na mala, com a escova de dentes, aschinelas, um revólver. Naquela mesma tarde, foi para a cerca, esperar avolta da fulana. E conversaram na porteira. Simão voltou, desatinado.Conversara a fulana. Queria um encontro, na manhã seguinte, no alto domorro.\r\n\r\nA outra não prometera nada. Ia ver, iaver. Simão estava possesso: – “Dez anos!”, e repetia, quase chorando: –“Dez anos não são dez dias!”. Campos do Jordão estava cheio de casosparecidos. Nada mais cruel do que a cronicidade de certas formas detuberculose. Eu conheci vários que haviam completado, lá na montanha,um quarto de século. E o próprio Simão falava dos dez anos como sefosse esta a idade do seu desejo.\r\n\r\nNa manhã seguinte, foi o primeiro aacordar. (…) Havia uma tosse da madrugada e uma tosse da manhã. Eu melembro daquele dia. Nunca se tossiu tanto. Sujeitos se torciam eretorciam asfixiados', 40),
(32, 1, 1, '(UFPA) Tecendo a manhã\r\n\r\nUm galo sozinho não tece uma manhã:\r\n\r\nele precisará sempre de outros galos.\r\n\r\nDe um que apanhe o grito que um galo antes\r\n\r\ne o lance a outro; e de outros galos\r\n\r\nque com muitos outros galos se cruzem\r\n\r\nos fios de sol de seus gritos de galo,\r\n\r\npara que a manhã, desde uma teia tênue,\r\n\r\nse vá tecendo, entre todos os galos.\r\n\r\nE se encorpando em tela, entre todos,\r\n\r\nse erguendo tenda, onde entrem todos,\r\n\r\nse entretendendo para todos, no toldo\r\n\r\n(a manhã) que plana livre de armação.\r\n\r\nA manhã, toldo de um tecido tão aéreo\r\n\r\nque, tecido, se eleva por si: luz balão.\r\n\r\n(MELO, João Cabral de. In: Poesias Completas. Rio de Janeiro, José Olympio, 1979)\r\n\r\nNos versos\r\n\r\n“E se encorpando em tela, entre todos,\r\n\r\nse erguendo tenda, onde entrem todos,\r\n\r\nse entretendendo para todos, no toldo…”\r\n\r\ntem-se exemplo de		\r\n	', 40),
(33, 1, 2, '(USP) O índio, em alguns romances de José de Alencar, como Iracema e Ubirajara, é: 		\r\n	', 60),
(34, 1, 2, '(PUC) Considerado pela crítica brasileira o escritor mais bem dotado de sua geração, Álvares de Azevedo, além das poesias, deixou-nos que obra de prosa narrativa? 		\r\n	', 60),
(35, 1, 3, '(FEI) Numere a coluna da esquerda, de acordo com a coluna da direita, tendo em vista a poesia romântica brasileira:\r\n\r\n1. primeira geração\r\n\r\n2. segunda geração\r\n\r\n3. terceira geração\r\n\r\n( ) abolicionismo\r\n\r\n( ) condoreirismo\r\n\r\n( ) autocomiseração exacerbada\r\n\r\n( ) obsessão pela morte\r\n\r\n( ) indianismo\r\n\r\n( ) nacionalismo\r\n\r\nAgora, escolha a alternativa que apresenta a seqüência correta dos numerais: 		\r\n	', 60),
(36, 2, 1, '(PUC-RIO 2010)\r\n\r\nEm uma turma de Ciências da Computação formada de 40rapazes e 40 moças, tem-se a seguinte estatística:20% dos rapazes são fumantes;30% das moças são fumantes.Logo, a porcentagem dos que não fumam na turma é de:		\r\n	', 40),
(37, 2, 2, '(PUC-RIO 2009)\r\n\r\nEm um viveiro há várias araras.\r\n\r\n    N 60% das araras são azuis,\r\n    N 40% das araras são vermelhas,\r\n    N 40% das araras azuis têm bico branco,\r\n    N 30% das araras vermelhas têm bico branco.\r\n\r\nQue porcentagem das araras do viveiro tem bico branco?		\r\n	', 40),
(38, 2, 1, '(PUC-RIO 2009)\r\n\r\nJoão recebeu um aumento de 10% e com isso seu salário chegou a R$1.320,00. O salário de João antes do aumento era igual a?		\r\n	', 40),
(39, 2, 2, '(PUC-RIO 2007)\r\n\r\nQue número deve ser somado ao numerador e ao denominador da fração 2/3 para que ela tenha um aumento de 25%?		\r\n	', 40),
(40, 2, 2, '(PUC-RIO 2007)\r\n\r\n30% de 30% são:		\r\n	', 80),
(41, 2, 1, '(UDESC 2010)\r\n\r\nSeu Antônio, um sujeito organizado e atento a promoções, decidiu pesquisar os preços de passagens aéreas, após ler a seguinte manchete:\r\n\r\n    “As medidas tomadas para aumentar a concorrência no setor aéreo já tiveram efeito. Os preços das passagens nacionais e internacionais baixaram. Esses preços podem ficar ainda menores se o consumidor se organizar.” (O Globo, 12/05/2009)\r\n\r\nSeu Antônio descobriu que certa empresa aérea estava operando o trajeto Florianópolis – São Paulo com um desconto de 40% durante o mês de novembro, e que esta empresa oferecia ainda um desconto adicional de 10%, às segundas-feiras. Ele então decidiu viajar em uma segunda-feira de novembro para economizar R$ 138,00, aproveitando esta promoção. O valor desta passagem, em reais, cobrado por esta empresa antes da promoção, era igual a:		\r\n	', 40),
(42, 2, 2, '(UDESC 2010)\r\n\r\nNo final do primeiro semestre deste ano, 40 acadêmicos participaram de uma pesquisa que objetivou analisar a frequência com que estes utilizaram o atendimento extraclasse do professor e/ou do monitor de uma determinada disciplina. Obteve-se o seguinte resultado: 20% dos acadêmicos procuraram atendimento tanto do professor quanto do monitor; 30% dos acadêmicos procuraram somente o atendimento do monitor; 15% dos acadêmicos não opinaram e 4 acadêmicos não procuraram atendimento do professor nem do monitor. Então o número de acadêmicos que procurou o atendimento somente do professor é igual a:		\r\n	', 40),
(43, 2, 1, '(UFMG 2010)\r\n\r\nO preço de venda de determinado produto tem a seguinte composição: 60% referentes ao custo, 10% referentes ao lucro e 30% referentes a impostos. Em decorrência da crise econômica, houve um aumento de 10% no custo desse produto, porém, ao mesmo tempo, ocorreu uma redução de 20% no valor dos impostos. Para aumentar as vendas do produto, o fabricante decidiu, então, reduzir seu lucro à metade.\r\n\r\nÉ CORRETO afirmar, portanto, que, depois de todas essas alterações, o preço do produto sofreu redução de:		\r\n	', 60),
(44, 2, 2, '(FUVEST 2009)\r\n\r\nHá um ano, Bruno comprou uma casa por R$ 50.000,00. Para isso, tomou emprestados R$ 10.000,00 de Edson e R$ 10.000,00 de Carlos, prometendo devolver-lhes o dinheiro, após um ano, acrescido de 5% e 4% de juros, respectivamente. A casa valorizou 3% durante este período de um ano.\r\n\r\nSabendo-se que Bruno vendeu a casa hoje e pagou o combinado a Edson e Carlos, o seu lucro foi de:		\r\n	', 40),
(45, 2, 1, '(UFPR 2010)\r\n\r\nPara testar a eficiência de um tratamento contra o câncer, foi selecionado um paciente que possuía um tumor de formato esférico, com raio de 3 cm. Após o início do tratamento, constatou-se, através de tomografias, que o raio desse tumor diminuiu a uma taxa de 2 mm por mês. Caso essa taxa de redução se mantenha, qual dos valores abaixo se aproxima mais do percentual do volume do tumor original que restará após 5 meses de tratamento?		\r\n	', 40),
(46, 5, 1, '(PUC-RIO 2010)\r\n\r\nUma quantidade de água líquida de massa m = 200 g, a uma temperatura de 30 Cº, é colocada em uma calorímetro junto a 150 g de gelo a 0 Cº. Após atingir o equilíbrio, dado que o calor específico da água é c = 1,0 cal/(g . Cº) e o calor latente de fusão do gelo é L = 80 cal/g, calcule a temperatura final da mistura gelo + água.		\r\n	', 40),
(47, 5, 2, '(PUC-RIO 2009)\r\n\r\nQuanta energia deve ser dada a uma panela de ferro de 300 g para que sua temperatura seja elevada em 100 ºC? Considere o calor específico da panela como c = 450 J/ kg ºC.		\r\n	', 60),
(48, 5, 3, '(PUC-RIO 2008)\r\n\r\nQuanto calor precisa ser dado a uma placa de vidro de 0,3 kg para aumentar sua temperatura em 80 °C? (Considere o calor específico do vidro como 70 J/kg °C)		\r\n	', 40),
(49, 5, 1, '(UFMG 2008)\r\n\r\nDepois de assar um bolo em um forno a gás, Zulmira observa que ela queima a mão ao tocar no tabuleiro, mas não a queima ao tocar no bolo. Considerando-se essa situação, é CORRETO afirmar que isso ocorre porque:		\r\n	', 40),
(50, 5, 2, '(UFAC/AC) – Uma espira circular de raio R é mantida próxima de um fioretilíneo muito grande percorrido por uma corrente I = 62,8 A. Qual ovalor da corrente que percorrerá a espira para que o campo magnéticoresultante no centro da espira seja nulo?		\r\n	', 60),
(51, 8, 2, '(UFU-MG)\r\n\r\nO átomo é a menor partícula que identifica um elemento químico. Ele possui duas partes, a saber: uma delas é o núcleo, constituído por prótons e nêutrons, e a outra é a região externa – a eletrosfera-, por onde circulam os elétrons. Alguns experimentos permitiram a descoberta das características das partículas constituintes do átomo.\r\n\r\nEm relação a essas características, indique a alternativa correta.		\r\n	', 40),
(52, 8, 2, 'Dados os átomos de 92U238  e 83Bi210, o número total de partículas (prótons, elétrons e nêutrons) existentes na somatória será:		\r\n	', 80),
(53, 8, 1, '(UFCE)\r\n\r\nNa tentativa de montar o intrincado quebra-cabeça da evolução humana, pesquisadores têm utilizado relações que envolvem elementos de mesmo número atômico e diferentes números de massa para fazer a datação de fósseis originados em sítios arqueológicos. Quanto a esses elementos, é correto afirmar que são:		\r\n	', 40),
(54, 8, 2, '(UFRJ)\r\n\r\nAlguns estudantes de Química, avaliando seus conhecimentos relativos a conceitos básicos para o estudo do átomo, analisam as seguintes afirmativas:\r\n\r\nI. Átomos isótopos são aqueles que possuem mesmo número atômico e números de massa diferentes.\r\n\r\nII. O número atômico de um elemento corresponde à soma do número de prótons com o de nêutrons.\r\n\r\nIII. O número de massa de um átomo, em particular, é a soma do número de prótons com o de elétrons.\r\n\r\nIV. Átomos isóbaros são aqueles que possuem números atômicos diferentes e mesmo número de massa.\r\n\r\nV. Átomos isótonos são aqueles que apresentam números atômicos diferentes, número de massas diferentes e mesmo número de nêutrons.\r\n\r\nEsses estudantes concluem, corretamente, que as afirmativas verdadeiras são as indicadas por:		\r\n	', 40),
(55, 8, 4, '(PUC-MG)\r\n\r\nO íon óxido O2- possui o mesmo número de elétrons que:\r\nDados: O (Z=8); F (Z=9); Na (Z=11); Ca (Z=20); S (Z=16);		\r\n	', 60),
(56, 6, 2, '(UEMA) Os novos movimentos sociais, principalmente os ambientalistas no Brasil e no mundo, têm se destacado no combate às indústrias poluidoras e usinas nucleares, ao desmatamento indiscriminado da Floresta Amazônica, dentre outros. Sobre esses movimentos, leia as proposições abaixo.\r\n\r\nI. São movimentos sociais preservacionistas que têm como objetivo salvar o planeta Terra das agressões do homem.\r\nII. São movimentos sociais que têm como ideologia revolucionar o modo de produção capitalista instaurando o socialismo.\r\nIII. São movimentos sociais que incriminam as empresas capitalistas modernas como devastadoras do planeta Terra.\r\nIV. São movimentos sociais que querem destruir o poder do Estado-Nação.\r\n\r\nÉ CORRETO o que se afirma em:		\r\n	', 40),
(57, 6, 1, '(UEMA) Assinale a alternativa que corresponde ao conceito de “Dominação Legítima”, formulada pelo sociólogo alemão Max Weber.\r\n		\r\n	', 40),
(58, 6, 2, '(UEMA) A globalização é um processo antigo que teve inicio com o desenvolvimento capitalista e sua expansão ultramarina. Dentre as proposições abaixo, assinale a alternativa que expressa esse processo nas suas configurações atuais.\r\n		\r\n	', 60),
(59, 6, 1, '(UEMA) Segundo Karl Marx,\r\n“o modo de produção da vida material condiciona o desenvolvimento da vida social, política e intelectual em geral”.\r\n\r\nEssa tese resume a sua teoria da história, também denominada de: 		\r\n	', 40),
(60, 6, 3, '(UFMA) Os principais fatos histórico-sociais que propiciaram o surgimento da sociologia foram:		\r\n	', 60),
(61, 6, 1, '(UFMA) Émile Durkheim (1858-1917) introduz no primeiro capítulo da sua obra As regras do método sociológico o conceito de: \r\n		\r\n	', 80),
(62, 6, 2, '(UFMA) Enumere a segunda coluna, de acordo com a primeira, relacionando as obras com seus respectivos autores e em seguida marque a opção que contém a seqüência correta da segunda coluna.\r\n\r\nPrimeira coluna:\r\n\r\n( ) O suicídio\r\n( ) A ética protestante e o espírito do capitalismo\r\n( ) O capital\r\n\r\nSegunda coluna:\r\n\r\n( ) Karl Marx (1818-1883)\r\n( ) Émile Durkheim (1858-1917)\r\n( ) Max Weber (1864-1920)', 40),
(63, 6, 2, '(UFMA) A afirmação segundo a qual o indivíduo tem consciência de seus direitos, deveres e de que participa ativamente de todas as questões da sociedade refere-se a:\r\n		\r\n	', 40),
(64, 6, 4, '(Enem 2012 - Primeiro Dia)\r\n\r\nNa regulação de matérias culturalmente delicadas, como, por exemplo, a linguagem oficial, os currículos da educação pública, o status das Igrejas e das comunidades religiosas, as normas do direito penal (por exemplo, quanto ao aborto), mas também em assuntos menos chamativos, como, por exemplo, a posição da família e dos consórcios semelhantes ao matrimônio, a aceitação de normas de segurança ou a delimitação das esferas pública e privada – em tudo isso refere-se amiúde apenas o auto entendimento ético-político de uma cultura majoritária, dominante por motivos históricos. Por causa de tais regras, implicitamente repressivas, mesmo dentro de uma comunidade republicana que garanta formalmente a igualdade de direitos para todos, pode eclodir um conflito cultural movido pelas minorias desprezadas contra a cultura da maioria.\r\n\r\n    HABERMAS, J. A inclusão do outro: estudos de teoria política. São Paulo: Loyola, 2002.\r\n\r\nA reivindicação dos direitos culturais das minorias, como exposto por Habermas, encontra amparo nas democracias contemporâneas, na medida em que se alcança\r\n		\r\n	', 40),
(65, 6, 1, '(Enem 2012 - Primeiro Dia) Uma mesma empresa pode ter sua sede administrativa onde os impostos são menores, as unidades de produção onde os salários são os mais baixos, os capitais onde os juros são os mais altos e seus executivos vivendo onde a qualidade de vida é mais elevada.\r\n\r\nSEVCENKO, N. A corrida para o século XXI: no loop da montanha russa. São Paulo: Companhia das Letras, 2001 (adaptado).\r\n\r\nNo texto estão apresentadas estratégias empresariais no contexto da globalização. Uma consequência social derivada dessas estratégias tem sido\r\n		\r\n	', 40),
(66, 7, 1, '(Enem 2012 - Primeiro Dia)\r\n\r\n    TEXTO I\r\n\r\n    Experimentei algumas vezes que os sentidos eram enganosos, e é de prudência nunca se fiar inteiramente em quem já nos enganou uma vez.\r\nDESCARTES, R. Meditações Metafísicas. São Paulo: Abril Cultural, 1979.\r\n\r\n    TEXTO II\r\n\r\n    Sempre que alimentarmos alguma suspeita de que uma ideia esteja sendo empregada sem nenhum significado, precisaremos apenas indagar: de que impressão deriva esta suposta ideia? E se for impossível atribuir-lhe qualquer impressão sensorial, isso servirá para confirmar nossa suspeita.\r\n\r\n    HUME, D. Uma investigação sobre o entendimento. São Paulo: Unesp, 2004 (adaptado).\r\n\r\nNos textos, ambos os autores se posicionam sobre a natureza do conhecimento humano. A comparação dos excertos permite assumir que Descartes e Hume\r\n		\r\n	', 60),
(67, 7, 3, '(Enem 2012 - Primeiro Dia)\r\n\r\n    TEXTO I\r\n\r\n    Anaxímenes de Mileto disse que o ar é o elemento originário de tudo o que existe, existiu e existirá, e que outras coisas provêm de sua descedência. Quando o ar se dilata, transforma-se em fogo, ao passo que os ventos são ar condensado. As nuvens formam-se a partir do ar por feltragem e, ainda mais condensadas, transformam-se em água. A água, quando mais condensada, transforma-se em terra, e quando condensada ao máximo possível, transforma-se em pedras.\r\n\r\n    BURNET, J. A aurora da filosofia grega. Rio de Janeiro: PUC-Rio, 2006 (adaptado).\r\n\r\n    TEXTO II\r\n\r\n    Basílio Magno, filósofo medieval, escreveu: “Deus, como criador de todas as coisas, está no princípio do mundo e dos tempos. Quão parcas de conteúdo se nos apresentam, em face desta concepção, as especulações contraditórias dos filósofos, para os quais o mundo se origina, ou de algum dos quatro elementos, como ensinam os Jônios, ou dos átomos, como julga Demócrito. Na verdade, dão impressão de quererem ancorar o mundo numa teia de aranha.”\r\n\r\n    GILSON, E.: BOEHNER, P. História da Filosofia Cristã. São Paulo: Vozes, 1991 (adaptado).\r\n\r\nFilósofos dos diversos tempos históricos desenvolveram teses para explicar a origem do universo, a partir de uma explicação racional. As teses de Anaxímenes, filósofo grego antigo, e de Basílio, filósofo medieval, têm em comum na sua fundamentação teorias que\r\n		\r\n	', 60),
(68, 7, 3, '(Enem 2012 - Primeiro Dia)\r\n\r\n    Para Platão, o que havia de verdadeiro em Parmênides era que o objeto de conhecimento é um objeto de razão e não de sensação, e era preciso estabelecer uma relação entre objeto racional e objeto sensível ou material que privilegiasse o primeiro em detrimento do segundo. Lenta, mas irresistivelmente, a Doutrina das Ideias formava-se em sua mente.\r\n\r\n    ZINGANO, M. Platão e Aristóteles: o fascínio da filosofia. São Paulo: Odysseus, 2012 (adaptado).\r\n\r\nO texto faz referência à relação entre razão e sensação, um aspecto essencial da Doutrina das Ideias de Platão (427 a.C.-346 a.C.). De acordo com o texto, como Platão se situa diante dessa relação?\r\n		\r\n	', 40),
(69, 7, 2, '(Enem 2012 - Primeiro Dia)\r\n\r\n    Esclarecimento é a saída do homem de sua menoridade, da qual ele próprio é culpado. A menoridade é a incapacidade de fazer uso de seu entendimento sem a direção de outro indivíduo. O homem é o próprio culpado dessa menoridade se a causa dela não se encontra na falta de entendimento, mas na falta de decisão e coragem de servir-se de si mesmo sem a direção de outrem. Tem coragem de fazer uso de teu próprio entendimento, tal é o lema do esclarecimento. A preguiça e a covardia são as causas pelas quais uma tão grande parte dos homens, depois que a natureza de há muito os libertou de uma condição estranha, continuem, no entanto, de bom grado menores durante toda a vida.\r\n\r\n    KANT, I. Resposta à pergunta: o que é esclarecimento? Petrópolis: Vozes, 1985 (adaptado).\r\n\r\nKant destaca no texto o conceito de Esclarecimento, fundamental para a compreensão do contexto filosófico da Modernidade. Esclarecimento, no sentido empregado por Kant, representa\r\n		\r\n	', 60),
(70, 7, 4, '(Unesp 2013 - Primeira Fase)\r\n\r\n    O marketing religioso objetiva identificar as necessidades de espírito e de conhecimento dos adeptos de uma determinada religião, oferecendo uma linha de produtos e serviços específicos para determinado segmento religioso e linguagem inerente ao tipo de pregação veiculada. A pessoa que se sente vazia num mundo capitalista e individualista busca refúgio através de uma religião. Identificar o público que mais frequenta o templo e o bairro onde o mesmo está situado, o nível de escolaridade, renda, hábitos, demais dados dos perfis demográficos e psicográficos são considerados num planejamento de marketing de uma linha de produtos religiosos.\r\n\r\n    (Fernando Rebouças. Marketing religioso. www.infoescola.com, 04.01.2010. Adaptado.)\r\n\r\nO fenômeno descrito pode ser explicado por tendências de\r\n		\r\n	', 40),
(71, 7, 2, '(Unesp 2013 - Primeira Fase)\r\n\r\n    O hormônio testosterona está ligado ao egoísmo, segundo uma pesquisa inglesa. Em testes feitos por cientistas da University College London, na Grã-Bretanha, mulheres que tomaram doses do hormônio masculino mostraram comportamento egocêntrico quando tinham de lidar com problemas em pares. Quando os pesquisadores ministraram placebo às voluntárias antes dos testes, elas cooperaram entre si. O estudo ajuda a explicar como os hormônios moldam o comportamento humano.\r\n\r\n    (Testosterona pode induzir comportamento egoísta. Veja, 01.02.2012.)\r\n\r\nO pressuposto fundamental assumido pela pesquisa citada para explicar o comportamento humano pode ser identificado com\r\n		\r\n	', 60),
(72, 7, 1, '(Unesp 2013 - Primeira Fase)\r\n\r\n    Em um documento rubricado pela Rede Global de Academias de Ciência (IAP), um grupo de pensadores da comunidade científica com sede em Trieste (Itália) que engloba 105 academias de todo o mundo alerta pela primeira vez sobre os riscos do consumo nos países do Primeiro Mundo e a falta de controle demográfico, prici palmente nas nações em desenvolvimento. Na declração da comunidade científica se indica que as pautas de consumo exarcebado do Primeiro Mundo estão se deslocando perigosamente para os países em desenvovimento: os milhões de telefones celulares e toneladas de “junk food” que invadem os lares pobres são claros indicadores dessa problemática. A ausência nos países pobres de políticas de planejamento familiar ou de prevenção de gravidezes precoces acaba de configurar um sombrio cenário de superpopulação. Trata-se de dois problemas convergentes que pela primeira vez analisamos de forma conjunta”, afirma García Novo.\r\n\r\n    (Francho Barón, El País, 16.06.2012. Adaptado)\r\n\r\nUm dos problemas relatados no texto está relacionado com\r\n		\r\n	', 80),
(73, 7, 2, '(Unesp 2013 - Primeira Fase)\r\n\r\n    Encontrar explicações convincentes para a origem e a evolução da vida sempre foi uma obsessão para os cientistas. A competição constante, embora muitas vezes silenciosa, entre os indivíduos, teria preservado as melhores linhagens, afirmava Charles Darwin. Assim, um ser vivo com uma mutação favorável para a sobrevivência da espécie teria mais chances de sobreviver e espalhar essa característica para as futuras gerações. Ao fim, sobreviveriam os mais fortes, como interpretou o filósofo Herbert Spencer. Um século e meio depois, um biólogo americano agita a comunidade científica interna cional ao ousar complementar a teoria da seleção darwinista. Segundo Edward Wilson, da Universidade de Harvard, o processo evolutivo é mais bem-sucedido em sociedades nas quais os indivíduos colaboram uns com os outros para um objetivo comum. Assim, grupos de pessoas, empresas e até países que agem pensando em benefício dos outros e de forma coletiva alcançam mais sucesso, segundo o americano.\r\n\r\n    (Rachel Costa. O poder da generosidade. IstoÉ. 11.05.2012. Adaptado)\r\n\r\nEmbora divergentes no que se refere aos fatores que explicam a evolução da espécie humana, ambas as teorias, de Darwin e de Wilson, apresentam como ponto comum a concepção de que\r\n		\r\n	', 60),
(74, 7, 3, '(Unesp 2013 - Primeira Fase)\r\n\r\n    Desde o início da semana, alunos da rede municipal de Vitória da Conquista, na Bahia, não vão mais poder cabular aulas. Um “uniforme inteligente” vai contar aos pais se os alunos chegaram à escola – ou “dedurar” se eles não passaram do portão. O sistema, baseado em rádio-frequência, funciona por meio de um minichip instalado na camiseta do novo uniforme, que começou a ser distribuído para 20 mil estudantes na segunda-feira.\r\n\r\n    Funciona assim: no momento em que os alunos entram na escola, um sensor instalado na portaria detecta o chip e envia um SMS aos pais avisando sobre a entrada na instituição.\r\n\r\n    (Natália Cancian. Uniforme inteligente entrega aluno que cabula aula na Bahia. Folha de S. Paulo, 22.03.2012)\r\n\r\nA leitura do fato relatado na reportagem permite repercussões filosóficas relacionadas à esfera da ética, pois o “uniforme inteligente”\r\n		\r\n	', 80),
(75, 7, 4, '(Unesp 2013 - Primeira Fase)\r\n\r\n    A modernidade não pertence a cultura nenhuma, mas surge sempre CONTRA uma cultura particular, como uma fenda, uma fissura no tecido desta. Assim, na Europa, a modernidade não surge como um desenvolvimento da cultura cristã, mas como uma crítica a esta, feita por indivíduos como Copérnico, Montaigne, Bruno, Descartes, indivíduos que, na medida em que a criticavam, já dela se separavam, já dela se desenraizavam. A crítica faz parte da razão que, não pertencendo a cultura particular nenhuma, está em princípio disponível a todos os seres humanos e culturas. Entendida desse modo, a moderni dade não consiste numa etapa da história da Europa ou do mundo, mas numa postura crítica ante a cultura, postura que é capaz de surgir em diferentes momentos e regiões do mundo, como na Atenas de Péricles, na Índia do imperador Ashoka ou no Brasil de hoje.\r\n\r\n    (Antonio Cícero. Resenha sobre o livro “O Roubo da História”. Folha de S. Paulo, 01.11.2008. Adaptado)\r\n\r\nCom a leitura do texto, a modernidade pode ser entendida como\r\n\r\n\r\n		\r\n	', 60),
(78, 5, 2, '(ITA/SP) - A figura mostra uma espira condutora que se desloca com velocidade constante v numa região com campo magnético uniforme no espaço e constante no tempo. Este campo magnético forma um ângulo q como plano da espira. A força eletromotriz máxima produzida pela variação de fluxo magnético no tempo ocorre quando', 60),
(79, 5, 3, '(FURG/RS) - Um fio condutor retilíneo e muito longo é percorrido por uma corrente elétrica constante, que cria um campo magnético em torno do fio. Podemos afirmar que esse campo magnético:		\r\n	', 60),
(80, 5, 2, '(UFLavras/01) - A figura abaixo mostra um fio condutorpercorrido por uma corrente i, imerso em um campo magnético de um imãna forma de U.\r\nA força magnética que atua nesse condutor faz com que este se desloque para	\r\n	', 40),
(81, 5, 1, '(Unifor/CE/Janeiro) - Um ímã, com certeza, NÃO atrai:		\r\n	', 40),
(82, 5, 2, '(Unifor/CE/02-Prova-Específica) - Dois condutores retilíneos,longos, muito finos, bem isolados e com corrente elétrica, se cruzamperpendicularmente, encostando um no outro sem que haja contatoelétrico. No plano determinado pelas retas suporte desses condutores,ficam bem determinados os quadrantes 1, 2, 3 e 4, conforme estáindicado no esquema.\r\n\r\nConsiderando os sentidos das correntes elétricas nos dois condutoresindicados no esquema, o campo magnético resultante dessas correnteselétricas é menos intenso nos quadrantes:		\r\n	', 60),
(83, 5, 1, '(UFMS/MS/Conh. Gerais) - Uma partícula eletricamente carregadae com uma energia cinética K, ao incidir perpendicularmente sobre umcampo magnético uniforme, sofre a ação de uma força magnética deintensidade F, descrevendo uma circunferência de raio R. É corretoafirmar que:		\r\n	', 80),
(84, 5, 2, '(Unifesp-SP/Fase-I) - A figura representa a vista de perfil deuma espira condutora retangular fechada, que pode girar em torno doeixo XY.\r\nSe essa espira for girada de 90, por uma força externa, de forma queseu plano, inicialmente paralelo às linhas do campo magnético uniformeB, se torne perpendicular a essas linhas, pode-se afirmar que:\r\n', 40),
(85, 5, 3, '(Unifenas-MG-Área-II) - O desenho representa um ímã X dividido em três partes.\r\nConsidere as afirmativas:\r\nI - As pontas A e C se repelem.\r\nII - As pontas B e D se atraem.\r\nIII - As pontas A e D se repelem.		\r\n	', 80),
(86, 5, 1, '(Unesp/SP) - A figura mostra um ímã em repouso, suspenso por um fio de massa desprezível e não magnetizável.\r\n\r\nEm seguida, um campo magnético uniforme é aplicado paralelamente ao solo, envolvendo todo o ímã, no sentido da esquerda para a direita da figura (pólo norte do campo à esquerda, e sul à direita). Analisando as forças magnéticas nos pólos do ímã, a força do fio sobre o ímã e o peso do ímã, identifique a alternativa que melhor representa as orientações assumidas pelo fio e pelo ímã no equilíbrio.		\r\n	', 40),
(87, 5, 1, '(Uni-Rio/RJ) - Três barras de ferro de mesma forma são identificadas pelas letras A, B, e C. Suas extremidades são identificadas\r\npor A1 e A2 , B1 e B2 e C1 e C2 . Quando estas barras são aproximadas vemos que as extremidades A1 e B1 sofrem\r\natração, as extremidades A1 e C2 sofrem repulsão, as extremidades A1 e B2 sofrem atração e as extremidades A1 e C1\r\nsofrem atração. Assim, podemos afirmar, em relação a estas barras, que é(são) ímã(s) permanente(s):		\r\n	', 40),
(88, 1, 2, '(USP) O índio, em alguns romances de José de Alencar, como Iracema e Ubirajara, é: 		\r\n	', 40),
(89, 1, 1, '(SANTA CASA) No conto "Um Homem Célebre", ocorre o falecimento da esposa do Pestana, personagem central, compositor que não logra concluir um réquiem para a missa da mulher. "Contentou-se da missa rezada e simples, para ele só. Não se pode dizer se todas as lágrimas que lhe vieram sorrateiramente aos olhos foram do marido, ou se algumas eram do compositor."\r\n\r\nConforme o excerto lembra, na obra de Machado de Assis é comum que o narrador: 		\r\n	', 60),
(90, 1, 2, '(SANTA CASA) "O poeta acorda na terra. Demais, o poeta é homem. "Homo sum", como dizia o célebre Romano. Vê, ouve, sente, e, o que é mais, sonha de noite as belas visões palpáveis de acordado. Tem nervos, tem fibra e tem artérias – isto é, antes e depois de ser um ente idealista, é um ente que tem corpo. E, digam o que quiserem, sem esses elementos, que sou o primeiro a reconhecer muito prosaicos, não há poesia".\r\n\r\nCom essas palavras, o poeta romântico Álvares de Azevedo valoriza o lado material do ser humano, deixando perceber concepções estéticas que poderiam ser consideradas precursoras da corrente literária: 		\r\n	', 80),
(91, 1, 1, '(SANTA CASA) "A primeira que se pôs a lavar foi a Leandra, por alcunha a "Machona", portuguesa feroz, berradora, pulsos cabeludos e grossos, anca de animal do campo".\r\n\r\nO texto permite afirmar que: 		\r\n	', 60),
(92, 1, 2, '(UEL) Assinale a alternativa que completa adequadamente a asserção:\r\n\r\nO Romantismo, graças à ideologia dominante e a um complexo conteúdo artístico, social e político, caracteriza-se como uma época propícia ao aparecimento de naturezas humanas marcadas por 		\r\n	', 40),
(93, 1, 1, '(FUVEST)\r\n\r\nI\r\n\r\nPorque não merecia o que lograva,\r\n\r\nDeixei, como ignorante, o bem que tinha,\r\n\r\nVim sem considerar aonde vinha,\r\n\r\nDeixei sem atender o que deixava.\r\n\r\nII\r\n\r\nSe a flauta mal cadente\r\n\r\nEntoa agora o verso harmonioso,\r\n\r\nSabei, me comunica este saudoso\r\n\r\nInfluxo a dor veemente;\r\n\r\nNão o gênio suave,\r\n\r\nQue ouviste já no acento agudo e grave.\r\n\r\nIII\r\n\r\nDa delirante embriaguez de bardo\r\n\r\nsonhos em que afoguei o ardor da vida,\r\n\r\nArdente orvalho de febris pranteios,\r\n\r\nQue lucro à alma descrita?"\r\n\r\nCada estrofe, a seu modo, trabalha o tema de um bem, de um amor almejado e passado ou perdido. Avaliando atentamente os recursos poéticos utilizados em cada uma delas podemos dizer que os movimentos literários a que pertencem I, II e III são respectivamente: 		\r\n	', 40),
(94, 1, 5, '(FUVEST) "Neste despropositado e inclassificável livro (...), não é que se quebre, mas enreda-se o fio das histórias e das observações por tal modo, que, bem o vejo e sinto, só com muita paciência se pode deslindar e seguir em tão embaraçada meada". Eis como o autor vê sua obra, dentro da qual faz reflexões como esta: "o povo, o povo está são: os corruptos somos nós os que cuidamos saber e ignoramos tudo." Trata-se da obra 		\r\n	', 60),
(95, 1, 3, '(FUVEST)\r\n\r\nI - Autor que levava no palco a sociedade portuguesa da primeira metade do século XVI, vivenciando, na expressão de Antônio José Saraiva, o reflexo da crise.\r\n\r\nII - Atuou na linha do teatro de costumes, associou o burlesco e o cômico em dramas e comédias ao retratar flagrantes da vida brasileira, do campo à cidade.\r\n\r\nOs enunciados referem-se, respectivamente, aos teatrólogos: 		\r\n	', 40),
(96, 1, 2, '(PUCCAMP)\r\n\r\n"Cantor das selvas, entre bravas matas\r\n\r\nÁspero tronco da palmeira escolho,\r\n\r\nUnido a ele soltarei meu canto,\r\n\r\nEnquanto o vento nos palmares zune,\r\n\r\nRugindo os longos, encontrados leques."\r\n\r\nOs versos acima, de Os Timbiras, de Gonçalves Dias, apresentam características da primeira geração romântica: 		\r\n	', 40),
(97, 1, 1, '(E. A. LAVRAS) "Vinha o passado e sentava-se num banco, tomando, a fresca ou tomando o luar".\r\n\r\nO passado, com sua melancolia, seu saudosismo, sua ternura, seu romantismo, não está presente na seguinte passagem do texto: 		\r\n	', 60),
(98, 2, 1, 'Qual deve ser a altitude do balão para que sua distância ao topo do prédio seja de 10 km?\r\n		\r\n	', 40),
(99, 2, 2, '(UFPB 2008)\r\n\r\nEm uma prova de rali, um carro percorreu 85% do percurso. Sabendo-se que faltam 180 km para completar a prova, é correto afirmar que o percurso total desse rali é:		\r\n	', 60),
(100, 2, 3, '(Enem 2014)\r\nDiesel é uma mistura de hidrocarbonetos que também apresenta enxofre em sua composição. Esse enxofre é um componente indesejável, pois o trióxido de enxofre gerado é um dos grandes causadores da chuva ácida. Nos anos 1980, não havia regulamentação e era utilizado óleo diesel com 13 000 ppm de enxofre. Em 2009, o diesel passou a ter 1 800 ppm de enxofre (S1800) e, em seguida, foi inserido no mercado o diesel S500 (500 ppm). Em 2012, foi difundido o diesel S50, com 50 ppm de enxofre em sua composição. Atualmente, é produzido um diesel com teores de enxofre ainda menores.\r\n\r\nOs impactos da má qualidade do óleo diesel brasileiro. Disponível em: www.cnt.org.br. Acesso em: 20 dez. 2012 (adaptado).\r\n\r\nA substituição do diesel usado nos anos 1980 por aquele difundido em 2012 permitiu uma redução percentual de emissão de SO3 de', 40),
(101, 2, 3, '(Enem 2011)\r\n\r\nUma pessoa aplicou certa quantia em ações. No primeiro mês, ela perdeu 30% do total do investimento e, no segundo mês, recuperou 20% do que havia perdido. Depois desses dois meses, resolveu tirar o montante de R$ 3 800,00 gerado pela aplicação. A quantia inicial que essa pessoa aplicou em ações corresponde ao valor de:		\r\n	', 60);
INSERT INTO `questions` (`id`, `disciplineId`, `difficulty`, `question`, `value`) VALUES
(102, 2, 2, '(Enem 2010)\r\n\r\nUm grupo de pacientes com Hepatite C foi submetido a um tratamento tradicional em que 40% desses pacientes foram completamente curados. Os pacientes que não obtiveram cura foram distribuídos em dois grupos de mesma quantidade e submetidos a dois tratamentos inovadores. No primeiro tratamento inovador, 35% dos pacientes foram curados e, no segundo, 45%. Em relação aos pacientes submetidos inicialmente, os tratamentos inovadores proporcionaram cura de:		\r\n	', 40),
(103, 4, 2, '(UFPA)\r\nO processo de industrialização e urbanização, nas grandes aglomerações urbanas, tem contribuído para o aumento de problemas e impactos ambientais. A respeito desses impactos, é correto afirmar que:		\r\n	', 40),
(104, 4, 1, '(UNIOESTE)\r\nSobre o clima mundial, os fatores e os processos que o condicionam, assinale a alternativa INCORRETA.\r\n\r\nI. A latitude influencia na distribuição espacial das temperaturas. Dessa forma, quanto maior for latitude, menores serão as temperaturas.\r\nII. A pressão atmosférica varia em função da altitude e da temperatura. Assim, quanto maior for a altitude, menor será a pressão atmosférica e quanto mais alta a temperatura, menor será a pressão.\r\nIII. O planeta Terra é aquecido uniformemente, tanto ao longo da sua superfície quanto ao longo do tempo (anos), e isto condiciona a circulação atmosférica com a produção de centros de alta e de baixa pressão, que se alteram continuadamente.\r\nIV. Dependendo das condições locais, a precipitação pode ocorrer na forma de chuva, granizo ou neve e está relacionada, principalmente, à umidade atmosférica.\r\nV. A diferença entre as temperaturas máxima e mínima é maior no interior dos continentes e a continentalidade exerce grande influência sobre essa amplitude térmica.		\r\n	', 40),
(105, 4, 2, '(UEPI)\r\nDepois de aproximadamente 11 minutos, a energia do Sol chega à Terra.Já que o Sol é muito maior que a Terra, os raios chegam praticamente paralelos entre si.\r\nEssa energia emitida pela estrela, importantíssima para a compreensão dos fenômenos meteorológicos e climáticos, é também denominada de:		\r\n	', 60),
(106, 4, 2, '(UNICAMP simulado 2011)\r\nA poluição nos grandes centros urbanos, como Curitiba, pode causar determinadas doenças como rinite, alergias, asma, problemas de pele e cabelo. Pessoas sensíveis às partículas em suspensão no ar podem desenvolver tais doenças ao respirar o ar poluído dos grandes centros.\r\nDurante todo o ano essas doenças podem acontecer, mas é no inverno que ficam mais acentuadas.\r\n(Adaptado de Jornal do Estado, Curitiba, 01/06/2009.)\r\n', 40),
(107, 4, 3, '(UFRN)\r\nNo dia 19 de junho de 2010, a cidade do Rio de Janeiro amanheceu sob a influência de um forte nevoeiro, que dificultava a visibilidade, interferindo no ritmo das atividades urbanas. O ar quente permaneceu acima da camada de ar frio, que ficou retida nas proximidades da superfície, favorecendo a concentração de poluentes. O que foi vivenciado nesta cidade é um fenômeno climático que pode ocorrer em qualquer época do ano, sendo mais comum no inverno. Nessa época, as chuvas são mais raras, dificultando, ainda mais, a dispersão dos poluentes, o que causa um problema ambiental.\r\n\r\nO fenômeno climático descrito no texto é conhecido como,		\r\n	', 40);

-- --------------------------------------------------------

--
-- Estrutura da tabela `ranking_data`
--

CREATE TABLE `ranking` (
  `id` int(4) NOT NULL,
  `userId` int(4) NOT NULL,
  `points` int(6) NOT NULL DEFAULT '0',
  `level` int(3) NOT NULL DEFAULT '1',
  `needPoints` int(6) NOT NULL DEFAULT '1000',
  `difficulty` int(1) NOT NULL DEFAULT '1',
  `rightAnswers` int(4) NOT NULL DEFAULT '0',
  `totalAnswers` int(4) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Estrutura da tabela `users`
--

CREATE TABLE `users` (
  `id` int(4) NOT NULL,
  `email` varchar(30) NOT NULL,
  `password` char(40) NOT NULL,
  `name` varchar(20) NOT NULL,
  `state` char(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for table `answers`
--
ALTER TABLE `answers`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `questions`
--
ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `ranking_data`
--
ALTER TABLE `ranking`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for table `answers`
--
ALTER TABLE `answers`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=108;

-- AUTO_INCREMENT for table `questions`
--
ALTER TABLE `questions`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=108;
--
-- AUTO_INCREMENT for table `ranking`
--
ALTER TABLE `ranking`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT;

--
-- ADD CONSTRAINT FOREIGN KEY ON ranking
--

ALTER TABLE ranking 
  ADD CONSTRAINT fk_user_ranking 
    FOREIGN KEY(userId)
      REFERENCES users(id)
        ON DELETE CASCADE 
          ON UPDATE CASCADE;
          
          